var classes = [
    {
        "name": "App\\Configs\\Config",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 0,
        "length": 9,
        "vocabulary": 9,
        "volume": 28.53,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0.01,
        "time": 0,
        "intelligentContent": 57.06,
        "number_operators": 0,
        "number_operands": 9,
        "number_operators_unique": 0,
        "number_operands_unique": 9,
        "cloc": 2,
        "loc": 16,
        "lloc": 14,
        "mi": 90.71,
        "mIwoC": 64.67,
        "commentWeight": 26.04,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\Configs\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "App\\Controllers\\AboutController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Views\\AboutTemplate"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 8,
        "lloc": 8,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "package": "App\\Controllers\\",
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Controllers\\BasketController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "add",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "clear",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 5,
        "ccn": 4,
        "ccnMethodMax": 4,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 2,
        "length": 34,
        "vocabulary": 11,
        "volume": 117.62,
        "difficulty": 2.89,
        "effort": 339.79,
        "level": 0.35,
        "bugs": 0.04,
        "time": 19,
        "intelligentContent": 40.71,
        "number_operators": 8,
        "number_operands": 26,
        "number_operators_unique": 2,
        "number_operands_unique": 9,
        "cloc": 5,
        "loc": 30,
        "lloc": 25,
        "mi": 84.03,
        "mIwoC": 54.47,
        "commentWeight": 29.56,
        "kanDefect": 0.36,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\Controllers\\",
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "App\\Controllers\\HomeController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Views\\HomeTemplate"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 8,
        "lloc": 8,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "package": "App\\Controllers\\",
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Controllers\\OrderController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "create",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "sendMail",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 10,
        "ccn": 8,
        "ccnMethodMax": 5,
        "externals": [
            "App\\Services\\ProductFactory",
            "App\\Views\\OrderTemplate",
            "App\\Services\\ValidateOrderData",
            "App\\Services\\ProductFactory",
            "App\\Services\\OrderFactory",
            "PHPMailer\\PHPMailer\\PHPMailer",
            "PHPMailer\\PHPMailer\\Exception"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 143,
        "vocabulary": 50,
        "volume": 807.07,
        "difficulty": 9.43,
        "effort": 7609.53,
        "level": 0.11,
        "bugs": 0.27,
        "time": 423,
        "intelligentContent": 85.6,
        "number_operators": 44,
        "number_operands": 99,
        "number_operators_unique": 8,
        "number_operands_unique": 42,
        "cloc": 15,
        "loc": 90,
        "lloc": 75,
        "mi": 67.22,
        "mIwoC": 37.67,
        "commentWeight": 29.56,
        "kanDefect": 0.66,
        "relativeStructuralComplexity": 196,
        "relativeDataComplexity": 0.42,
        "relativeSystemComplexity": 196.42,
        "totalStructuralComplexity": 588,
        "totalDataComplexity": 1.27,
        "totalSystemComplexity": 589.27,
        "package": "App\\Controllers\\",
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 6,
        "instability": 0.86,
        "violations": {}
    },
    {
        "name": "App\\Controllers\\ProductController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 4,
        "ccnMethodMax": 4,
        "externals": [
            "App\\Models\\Product",
            "App\\Views\\ProductTemplate",
            "App\\Views\\ProductTemplate",
            "App\\Views\\ProductTemplate"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 25,
        "vocabulary": 11,
        "volume": 86.49,
        "difficulty": 8.4,
        "effort": 726.48,
        "level": 0.12,
        "bugs": 0.03,
        "time": 40,
        "intelligentContent": 10.3,
        "number_operators": 11,
        "number_operands": 14,
        "number_operators_unique": 6,
        "number_operands_unique": 5,
        "cloc": 0,
        "loc": 18,
        "lloc": 18,
        "mi": 58.52,
        "mIwoC": 58.52,
        "commentWeight": 0,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1.33,
        "relativeSystemComplexity": 5.33,
        "totalStructuralComplexity": 4,
        "totalDataComplexity": 1.33,
        "totalSystemComplexity": 5.33,
        "package": "App\\Controllers\\",
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "App\\Models\\Product",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "loadData",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getBasketData",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "saveData",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 8,
        "ccn": 6,
        "ccnMethodMax": 5,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 2,
        "length": 107,
        "vocabulary": 26,
        "volume": 502.95,
        "difficulty": 11.55,
        "effort": 5809.04,
        "level": 0.09,
        "bugs": 0.17,
        "time": 323,
        "intelligentContent": 43.55,
        "number_operators": 30,
        "number_operands": 77,
        "number_operators_unique": 6,
        "number_operands_unique": 20,
        "cloc": 5,
        "loc": 57,
        "lloc": 52,
        "mi": 64.99,
        "mIwoC": 42.84,
        "commentWeight": 22.15,
        "kanDefect": 0.66,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1.17,
        "relativeSystemComplexity": 2.17,
        "totalStructuralComplexity": 3,
        "totalDataComplexity": 3.5,
        "totalSystemComplexity": 6.5,
        "package": "App\\Models\\",
        "pageRank": 0.05,
        "afferentCoupling": 2,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "App\\Router\\Router",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "route",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 7,
        "ccn": 7,
        "ccnMethodMax": 7,
        "externals": [
            "App\\Controllers\\AboutController",
            "App\\Controllers\\OrderController",
            "App\\Controllers\\BasketController",
            "App\\Controllers\\ProductController",
            "App\\Controllers\\BasketController",
            "App\\Controllers\\HomeController"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 66,
        "vocabulary": 26,
        "volume": 310.23,
        "difficulty": 3.07,
        "effort": 950.92,
        "level": 0.33,
        "bugs": 0.1,
        "time": 53,
        "intelligentContent": 101.21,
        "number_operators": 19,
        "number_operands": 47,
        "number_operators_unique": 3,
        "number_operands_unique": 23,
        "cloc": 1,
        "loc": 38,
        "lloc": 37,
        "mi": 59.84,
        "mIwoC": 47.4,
        "commentWeight": 12.43,
        "kanDefect": 0.37,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 1.75,
        "relativeSystemComplexity": 10.75,
        "totalStructuralComplexity": 9,
        "totalDataComplexity": 1.75,
        "totalSystemComplexity": 10.75,
        "package": "App\\Router\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 5,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Services\\DBStorage",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "PDO"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 2,
        "vocabulary": 2,
        "volume": 2,
        "difficulty": 0.5,
        "effort": 1,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 4,
        "number_operators": 1,
        "number_operands": 1,
        "number_operators_unique": 1,
        "number_operands_unique": 1,
        "cloc": 1,
        "loc": 10,
        "lloc": 9,
        "mi": 100.47,
        "mIwoC": 76.94,
        "commentWeight": 23.53,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\Services\\",
        "pageRank": 0.06,
        "afferentCoupling": 2,
        "efferentCoupling": 1,
        "instability": 0.33,
        "violations": {}
    },
    {
        "name": "App\\Services\\FileStorage",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "loadData",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "saveData",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "App\\Services\\ILoadStorage",
            "App\\Services\\ISaveStorage"
        ],
        "parents": [],
        "implements": [
            "App\\Services\\ILoadStorage",
            "App\\Services\\ISaveStorage"
        ],
        "lcom": 2,
        "length": 50,
        "vocabulary": 14,
        "volume": 190.37,
        "difficulty": 9.72,
        "effort": 1850.8,
        "level": 0.1,
        "bugs": 0.06,
        "time": 103,
        "intelligentContent": 19.58,
        "number_operators": 15,
        "number_operands": 35,
        "number_operators_unique": 5,
        "number_operands_unique": 9,
        "cloc": 0,
        "loc": 29,
        "lloc": 29,
        "mi": 51.87,
        "mIwoC": 51.87,
        "commentWeight": 0,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 3.5,
        "relativeSystemComplexity": 3.5,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 7,
        "totalSystemComplexity": 7,
        "package": "App\\Services\\",
        "pageRank": 0.03,
        "afferentCoupling": 2,
        "efferentCoupling": 2,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Services\\OrderDBStorage",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "saveData",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "saveItems",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "App\\Services\\DBStorage",
            "App\\Services\\ISaveStorage"
        ],
        "parents": [
            "App\\Services\\DBStorage"
        ],
        "implements": [
            "App\\Services\\ISaveStorage"
        ],
        "lcom": 1,
        "length": 76,
        "vocabulary": 26,
        "volume": 357.23,
        "difficulty": 4.11,
        "effort": 1467.76,
        "level": 0.24,
        "bugs": 0.12,
        "time": 82,
        "intelligentContent": 86.95,
        "number_operators": 13,
        "number_operands": 63,
        "number_operators_unique": 3,
        "number_operands_unique": 23,
        "cloc": 6,
        "loc": 32,
        "lloc": 26,
        "mi": 82.07,
        "mIwoC": 50.99,
        "commentWeight": 31.08,
        "kanDefect": 0.38,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0.8,
        "relativeSystemComplexity": 16.8,
        "totalStructuralComplexity": 32,
        "totalDataComplexity": 1.6,
        "totalSystemComplexity": 33.6,
        "package": "App\\Services\\",
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "App\\Services\\OrderFactory",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "createOrder",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "App\\Models\\Order",
            "App\\Services\\FileStorage",
            "App\\Models\\Order",
            "App\\Services\\OrderDBStorage",
            "App\\Models\\Order"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 16,
        "vocabulary": 6,
        "volume": 41.36,
        "difficulty": 7,
        "effort": 289.52,
        "level": 0.14,
        "bugs": 0.01,
        "time": 16,
        "intelligentContent": 5.91,
        "number_operators": 9,
        "number_operands": 7,
        "number_operators_unique": 4,
        "number_operands_unique": 2,
        "cloc": 0,
        "loc": 16,
        "lloc": 16,
        "mi": 62.01,
        "mIwoC": 62.01,
        "commentWeight": 0,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 1,
        "package": "App\\Services\\",
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 3,
        "instability": 0.75,
        "violations": {}
    },
    {
        "name": "App\\Services\\ProductDBStorage",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "loadData",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Services\\DBStorage",
            "App\\Services\\ILoadStorage"
        ],
        "parents": [
            "App\\Services\\DBStorage"
        ],
        "implements": [
            "App\\Services\\ILoadStorage"
        ],
        "lcom": 1,
        "length": 13,
        "vocabulary": 8,
        "volume": 39,
        "difficulty": 1.5,
        "effort": 58.5,
        "level": 0.67,
        "bugs": 0.01,
        "time": 3,
        "intelligentContent": 26,
        "number_operators": 4,
        "number_operands": 9,
        "number_operators_unique": 2,
        "number_operands_unique": 6,
        "cloc": 0,
        "loc": 11,
        "lloc": 11,
        "mi": 66.01,
        "mIwoC": 66.01,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0.67,
        "relativeSystemComplexity": 4.67,
        "totalStructuralComplexity": 4,
        "totalDataComplexity": 0.67,
        "totalSystemComplexity": 4.67,
        "package": "App\\Services\\",
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "App\\Services\\ProductFactory",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "createProduct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "App\\Models\\Product",
            "App\\Services\\FileStorage",
            "App\\Models\\Product",
            "App\\Services\\ProductDBStorage",
            "App\\Models\\Product"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 16,
        "vocabulary": 6,
        "volume": 41.36,
        "difficulty": 7,
        "effort": 289.52,
        "level": 0.14,
        "bugs": 0.01,
        "time": 16,
        "intelligentContent": 5.91,
        "number_operators": 9,
        "number_operands": 7,
        "number_operators_unique": 4,
        "number_operands_unique": 2,
        "cloc": 0,
        "loc": 16,
        "lloc": 16,
        "mi": 62.01,
        "mIwoC": 62.01,
        "commentWeight": 0,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 1,
        "package": "App\\Services\\",
        "pageRank": 0.03,
        "afferentCoupling": 1,
        "efferentCoupling": 3,
        "instability": 0.75,
        "violations": {}
    },
    {
        "name": "App\\Services\\ValidateOrderData",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "validate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 10,
        "ccn": 10,
        "ccnMethodMax": 10,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 67,
        "vocabulary": 28,
        "volume": 322.09,
        "difficulty": 7.17,
        "effort": 2308.33,
        "level": 0.14,
        "bugs": 0.11,
        "time": 128,
        "intelligentContent": 44.94,
        "number_operators": 24,
        "number_operands": 43,
        "number_operators_unique": 7,
        "number_operands_unique": 21,
        "cloc": 4,
        "loc": 33,
        "lloc": 29,
        "mi": 74.87,
        "mIwoC": 49.19,
        "commentWeight": 25.68,
        "kanDefect": 0.5,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 7,
        "relativeSystemComplexity": 7,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 7,
        "totalSystemComplexity": 7,
        "package": "App\\Services\\",
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "App\\Views\\AboutTemplate",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "getTemplate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Views\\BaseTemplate"
        ],
        "parents": [
            "App\\Views\\BaseTemplate"
        ],
        "implements": [],
        "lcom": 1,
        "length": 15,
        "vocabulary": 8,
        "volume": 45,
        "difficulty": 1.67,
        "effort": 75,
        "level": 0.6,
        "bugs": 0.02,
        "time": 4,
        "intelligentContent": 27,
        "number_operators": 5,
        "number_operands": 10,
        "number_operators_unique": 2,
        "number_operands_unique": 6,
        "cloc": 0,
        "loc": 17,
        "lloc": 17,
        "mi": 61.45,
        "mIwoC": 61.45,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "package": "App\\Views\\",
        "pageRank": 0.05,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Views\\BaseTemplate",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "getTemplate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 22,
        "vocabulary": 12,
        "volume": 78.87,
        "difficulty": 4,
        "effort": 315.48,
        "level": 0.25,
        "bugs": 0.03,
        "time": 18,
        "intelligentContent": 19.72,
        "number_operators": 6,
        "number_operands": 16,
        "number_operators_unique": 4,
        "number_operands_unique": 8,
        "cloc": 0,
        "loc": 79,
        "lloc": 75,
        "mi": 45.41,
        "mIwoC": 45.41,
        "commentWeight": 0,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 1,
        "package": "App\\Views\\",
        "pageRank": 0.32,
        "afferentCoupling": 4,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "App\\Views\\HomeTemplate",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "getTemplate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Views\\BaseTemplate"
        ],
        "parents": [
            "App\\Views\\BaseTemplate"
        ],
        "implements": [],
        "lcom": 1,
        "length": 15,
        "vocabulary": 8,
        "volume": 45,
        "difficulty": 1.67,
        "effort": 75,
        "level": 0.6,
        "bugs": 0.02,
        "time": 4,
        "intelligentContent": 27,
        "number_operators": 5,
        "number_operands": 10,
        "number_operators_unique": 2,
        "number_operands_unique": 6,
        "cloc": 0,
        "loc": 38,
        "lloc": 38,
        "mi": 53.83,
        "mIwoC": 53.83,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "package": "App\\Views\\",
        "pageRank": 0.05,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Views\\OrderTemplate",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "getOrderTemplate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "App\\Views\\BaseTemplate"
        ],
        "parents": [
            "App\\Views\\BaseTemplate"
        ],
        "implements": [],
        "lcom": 1,
        "length": 72,
        "vocabulary": 32,
        "volume": 360,
        "difficulty": 7.42,
        "effort": 2671.2,
        "level": 0.13,
        "bugs": 0.12,
        "time": 148,
        "intelligentContent": 48.52,
        "number_operators": 19,
        "number_operands": 53,
        "number_operators_unique": 7,
        "number_operands_unique": 25,
        "cloc": 0,
        "loc": 96,
        "lloc": 94,
        "mi": 38.66,
        "mIwoC": 38.66,
        "commentWeight": 0,
        "kanDefect": 0.45,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 2,
        "package": "App\\Views\\",
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Views\\ProductTemplate",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "getCardTemplate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getAllTemplate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 3,
        "ccnMethodMax": 2,
        "externals": [
            "App\\Views\\BaseTemplate"
        ],
        "parents": [
            "App\\Views\\BaseTemplate"
        ],
        "implements": [],
        "lcom": 2,
        "length": 87,
        "vocabulary": 39,
        "volume": 459.83,
        "difficulty": 4.11,
        "effort": 1891.87,
        "level": 0.24,
        "bugs": 0.15,
        "time": 105,
        "intelligentContent": 111.76,
        "number_operators": 15,
        "number_operands": 72,
        "number_operators_unique": 4,
        "number_operands_unique": 35,
        "cloc": 1,
        "loc": 73,
        "lloc": 72,
        "mi": 49.45,
        "mIwoC": 40.44,
        "commentWeight": 9.02,
        "kanDefect": 0.45,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1.5,
        "relativeSystemComplexity": 2.5,
        "totalStructuralComplexity": 2,
        "totalDataComplexity": 3,
        "totalSystemComplexity": 5,
        "package": "App\\Views\\",
        "pageRank": 0.04,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    }
]