var classes = [
    {
        "name": "App\\Configs\\Config",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 0,
        "length": 9,
        "vocabulary": 9,
        "volume": 28.53,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0.01,
        "time": 0,
        "intelligentContent": 57.06,
        "number_operators": 0,
        "number_operands": 9,
        "number_operators_unique": 0,
        "number_operands_unique": 9,
        "cloc": 5,
        "loc": 19,
        "lloc": 14,
        "mi": 100.36,
        "mIwoC": 64.67,
        "commentWeight": 35.68,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\Configs\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "App\\Controllers\\AboutController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Views\\AboutTemplate"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 8,
        "lloc": 8,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "package": "App\\Controllers\\",
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Controllers\\BasketController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "add",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "clear",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 5,
        "ccn": 4,
        "ccnMethodMax": 4,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 2,
        "length": 38,
        "vocabulary": 12,
        "volume": 136.23,
        "difficulty": 2.9,
        "effort": 395.06,
        "level": 0.34,
        "bugs": 0.05,
        "time": 22,
        "intelligentContent": 46.98,
        "number_operators": 9,
        "number_operands": 29,
        "number_operators_unique": 2,
        "number_operands_unique": 10,
        "cloc": 7,
        "loc": 33,
        "lloc": 26,
        "mi": 86.38,
        "mIwoC": 53.65,
        "commentWeight": 32.72,
        "kanDefect": 0.36,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\Controllers\\",
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "App\\Controllers\\HomeController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Views\\HomeTemplate"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 1,
        "loc": 9,
        "lloc": 8,
        "mi": 195.69,
        "mIwoC": 171,
        "commentWeight": 24.69,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "package": "App\\Controllers\\",
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Controllers\\OrderController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "create",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "validate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "sendMail",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 26,
        "ccn": 23,
        "ccnMethodMax": 10,
        "externals": [
            "App\\Services\\FileStorage",
            "App\\Models\\Product",
            "App\\Services\\ProductDBStorage",
            "App\\Models\\Product",
            "App\\Views\\OrderTemplate",
            "App\\Services\\FileStorage",
            "App\\Models\\Product",
            "App\\Services\\ProductDBStorage",
            "App\\Models\\Product",
            "App\\Services\\FileStorage",
            "App\\Models\\Order",
            "App\\Services\\OrderDBStorage",
            "App\\Models\\Order",
            "PHPMailer\\PHPMailer\\PHPMailer",
            "PHPMailer\\PHPMailer\\Exception"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 247,
        "vocabulary": 67,
        "volume": 1498.32,
        "difficulty": 17.24,
        "effort": 25825.66,
        "level": 0.06,
        "bugs": 0.5,
        "time": 1435,
        "intelligentContent": 86.93,
        "number_operators": 89,
        "number_operands": 158,
        "number_operators_unique": 12,
        "number_operands_unique": 55,
        "cloc": 20,
        "loc": 141,
        "lloc": 121,
        "mi": 56.78,
        "mIwoC": 29.24,
        "commentWeight": 27.55,
        "kanDefect": 1.43,
        "relativeStructuralComplexity": 144,
        "relativeDataComplexity": 0.96,
        "relativeSystemComplexity": 144.96,
        "totalStructuralComplexity": 576,
        "totalDataComplexity": 3.85,
        "totalSystemComplexity": 579.85,
        "package": "App\\Controllers\\",
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 8,
        "instability": 0.89,
        "violations": {}
    },
    {
        "name": "App\\Controllers\\ProductController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 6,
        "ccnMethodMax": 6,
        "externals": [
            "App\\Services\\FileStorage",
            "App\\Models\\Product",
            "App\\Services\\ProductDBStorage",
            "App\\Models\\Product",
            "App\\Views\\ProductTemplate",
            "App\\Views\\ProductTemplate",
            "App\\Views\\ProductTemplate"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 37,
        "vocabulary": 13,
        "volume": 136.92,
        "difficulty": 11.08,
        "effort": 1517.49,
        "level": 0.09,
        "bugs": 0.05,
        "time": 84,
        "intelligentContent": 12.35,
        "number_operators": 18,
        "number_operands": 19,
        "number_operators_unique": 7,
        "number_operands_unique": 6,
        "cloc": 0,
        "loc": 25,
        "lloc": 25,
        "mi": 53.74,
        "mIwoC": 53.74,
        "commentWeight": 0,
        "kanDefect": 0.43,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1.33,
        "relativeSystemComplexity": 5.33,
        "totalStructuralComplexity": 4,
        "totalDataComplexity": 1.33,
        "totalSystemComplexity": 5.33,
        "package": "App\\Controllers\\",
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 4,
        "instability": 0.8,
        "violations": {}
    },
    {
        "name": "App\\Models\\Order",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "saveData",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Services\\ISaveStorage"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 13,
        "vocabulary": 6,
        "volume": 33.6,
        "difficulty": 2.5,
        "effort": 84.01,
        "level": 0.4,
        "bugs": 0.01,
        "time": 5,
        "intelligentContent": 13.44,
        "number_operators": 3,
        "number_operands": 10,
        "number_operators_unique": 2,
        "number_operands_unique": 4,
        "cloc": 1,
        "loc": 16,
        "lloc": 15,
        "mi": 82.41,
        "mIwoC": 63.52,
        "commentWeight": 18.88,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1.25,
        "relativeSystemComplexity": 2.25,
        "totalStructuralComplexity": 2,
        "totalDataComplexity": 2.5,
        "totalSystemComplexity": 4.5,
        "package": "App\\Models\\",
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Models\\Product",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "loadData",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getBasketData",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 7,
        "ccn": 5,
        "ccnMethodMax": 5,
        "externals": [
            "App\\Services\\ILoadStorage"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 67,
        "vocabulary": 16,
        "volume": 268,
        "difficulty": 8.33,
        "effort": 2233.33,
        "level": 0.12,
        "bugs": 0.09,
        "time": 124,
        "intelligentContent": 32.16,
        "number_operators": 17,
        "number_operands": 50,
        "number_operators_unique": 4,
        "number_operands_unique": 12,
        "cloc": 6,
        "loc": 43,
        "lloc": 37,
        "mi": 75.46,
        "mIwoC": 48.12,
        "commentWeight": 27.35,
        "kanDefect": 0.59,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1.33,
        "relativeSystemComplexity": 2.33,
        "totalStructuralComplexity": 3,
        "totalDataComplexity": 4,
        "totalSystemComplexity": 7,
        "package": "App\\Models\\",
        "pageRank": 0.03,
        "afferentCoupling": 2,
        "efferentCoupling": 1,
        "instability": 0.33,
        "violations": {}
    },
    {
        "name": "App\\Router\\Router",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "route",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 7,
        "ccn": 7,
        "ccnMethodMax": 7,
        "externals": [
            "App\\Controllers\\AboutController",
            "App\\Controllers\\ProductController",
            "App\\Controllers\\BasketController",
            "App\\Controllers\\OrderController",
            "App\\Controllers\\BasketController",
            "App\\Controllers\\HomeController"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 66,
        "vocabulary": 25,
        "volume": 306.49,
        "difficulty": 3.2,
        "effort": 982.18,
        "level": 0.31,
        "bugs": 0.1,
        "time": 55,
        "intelligentContent": 95.64,
        "number_operators": 19,
        "number_operands": 47,
        "number_operators_unique": 3,
        "number_operands_unique": 22,
        "cloc": 4,
        "loc": 41,
        "lloc": 37,
        "mi": 70.7,
        "mIwoC": 47.44,
        "commentWeight": 23.26,
        "kanDefect": 0.37,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 1.75,
        "relativeSystemComplexity": 10.75,
        "totalStructuralComplexity": 9,
        "totalDataComplexity": 1.75,
        "totalSystemComplexity": 10.75,
        "package": "App\\Router\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 5,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Services\\DatabaseStorage",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "loadData",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "saveData",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Services\\IStorage"
        ],
        "parents": [],
        "implements": [
            "App\\Services\\IStorage"
        ],
        "lcom": 2,
        "length": 5,
        "vocabulary": 3,
        "volume": 7.92,
        "difficulty": 0.75,
        "effort": 5.94,
        "level": 1.33,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 10.57,
        "number_operators": 2,
        "number_operands": 3,
        "number_operators_unique": 1,
        "number_operands_unique": 2,
        "cloc": 2,
        "loc": 14,
        "lloc": 12,
        "mi": 97.66,
        "mIwoC": 70.03,
        "commentWeight": 27.63,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 3.5,
        "relativeSystemComplexity": 3.5,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 7,
        "totalSystemComplexity": 7,
        "package": "App\\Services\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Services\\DBStorage",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "PDO"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 2,
        "vocabulary": 2,
        "volume": 2,
        "difficulty": 0.5,
        "effort": 1,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 4,
        "number_operators": 1,
        "number_operands": 1,
        "number_operators_unique": 1,
        "number_operands_unique": 1,
        "cloc": 1,
        "loc": 10,
        "lloc": 9,
        "mi": 100.47,
        "mIwoC": 76.94,
        "commentWeight": 23.53,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\Services\\",
        "pageRank": 0.05,
        "afferentCoupling": 2,
        "efferentCoupling": 1,
        "instability": 0.33,
        "violations": {}
    },
    {
        "name": "App\\Services\\FileStorage",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "loadData",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "saveData",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "App\\Services\\ILoadStorage",
            "App\\Services\\ISaveStorage"
        ],
        "parents": [],
        "implements": [
            "App\\Services\\ILoadStorage",
            "App\\Services\\ISaveStorage"
        ],
        "lcom": 2,
        "length": 50,
        "vocabulary": 14,
        "volume": 190.37,
        "difficulty": 9.72,
        "effort": 1850.8,
        "level": 0.1,
        "bugs": 0.06,
        "time": 103,
        "intelligentContent": 19.58,
        "number_operators": 15,
        "number_operands": 35,
        "number_operators_unique": 5,
        "number_operands_unique": 9,
        "cloc": 0,
        "loc": 29,
        "lloc": 29,
        "mi": 51.87,
        "mIwoC": 51.87,
        "commentWeight": 0,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 3.5,
        "relativeSystemComplexity": 3.5,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 7,
        "totalSystemComplexity": 7,
        "package": "App\\Services\\",
        "pageRank": 0.03,
        "afferentCoupling": 2,
        "efferentCoupling": 2,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Services\\OrderDBStorage",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "saveData",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "saveItems",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "loadData",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 4,
        "ccnMethodMax": 3,
        "externals": [
            "App\\Services\\DBStorage",
            "App\\Services\\ISaveStorage",
            "Exception",
            "Exception"
        ],
        "parents": [
            "App\\Services\\DBStorage"
        ],
        "implements": [
            "App\\Services\\ISaveStorage"
        ],
        "lcom": 2,
        "length": 91,
        "vocabulary": 38,
        "volume": 477.56,
        "difficulty": 5.68,
        "effort": 2713.42,
        "level": 0.18,
        "bugs": 0.16,
        "time": 151,
        "intelligentContent": 84.05,
        "number_operators": 16,
        "number_operands": 75,
        "number_operators_unique": 5,
        "number_operands_unique": 33,
        "cloc": 6,
        "loc": 47,
        "lloc": 41,
        "mi": 71.81,
        "mIwoC": 45.52,
        "commentWeight": 26.28,
        "kanDefect": 0.52,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0.52,
        "relativeSystemComplexity": 36.52,
        "totalStructuralComplexity": 108,
        "totalDataComplexity": 1.57,
        "totalSystemComplexity": 109.57,
        "package": "App\\Services\\",
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 3,
        "instability": 0.75,
        "violations": {}
    },
    {
        "name": "App\\Services\\ProductDBStorage",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "loadData",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Services\\DBStorage",
            "App\\Services\\ILoadStorage"
        ],
        "parents": [
            "App\\Services\\DBStorage"
        ],
        "implements": [
            "App\\Services\\ILoadStorage"
        ],
        "lcom": 1,
        "length": 13,
        "vocabulary": 8,
        "volume": 39,
        "difficulty": 1.5,
        "effort": 58.5,
        "level": 0.67,
        "bugs": 0.01,
        "time": 3,
        "intelligentContent": 26,
        "number_operators": 4,
        "number_operands": 9,
        "number_operators_unique": 2,
        "number_operands_unique": 6,
        "cloc": 0,
        "loc": 11,
        "lloc": 11,
        "mi": 66.01,
        "mIwoC": 66.01,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0.67,
        "relativeSystemComplexity": 4.67,
        "totalStructuralComplexity": 4,
        "totalDataComplexity": 0.67,
        "totalSystemComplexity": 4.67,
        "package": "App\\Services\\",
        "pageRank": 0.02,
        "afferentCoupling": 2,
        "efferentCoupling": 2,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Views\\AboutTemplate",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "getTemplate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Views\\BaseTemplate"
        ],
        "parents": [
            "App\\Views\\BaseTemplate"
        ],
        "implements": [],
        "lcom": 1,
        "length": 15,
        "vocabulary": 8,
        "volume": 45,
        "difficulty": 1.67,
        "effort": 75,
        "level": 0.6,
        "bugs": 0.02,
        "time": 4,
        "intelligentContent": 27,
        "number_operators": 5,
        "number_operands": 10,
        "number_operators_unique": 2,
        "number_operands_unique": 6,
        "cloc": 0,
        "loc": 17,
        "lloc": 17,
        "mi": 61.45,
        "mIwoC": 61.45,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "package": "App\\Views\\",
        "pageRank": 0.05,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Views\\BaseTemplate",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "getTemplate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 22,
        "vocabulary": 12,
        "volume": 78.87,
        "difficulty": 4,
        "effort": 315.48,
        "level": 0.25,
        "bugs": 0.03,
        "time": 18,
        "intelligentContent": 19.72,
        "number_operators": 6,
        "number_operands": 16,
        "number_operators_unique": 4,
        "number_operands_unique": 8,
        "cloc": 1,
        "loc": 71,
        "lloc": 70,
        "mi": 55.21,
        "mIwoC": 46.07,
        "commentWeight": 9.14,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 1,
        "package": "App\\Views\\",
        "pageRank": 0.29,
        "afferentCoupling": 4,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "App\\Views\\HomeTemplate",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "getTemplate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Views\\BaseTemplate"
        ],
        "parents": [
            "App\\Views\\BaseTemplate"
        ],
        "implements": [],
        "lcom": 1,
        "length": 15,
        "vocabulary": 8,
        "volume": 45,
        "difficulty": 1.67,
        "effort": 75,
        "level": 0.6,
        "bugs": 0.02,
        "time": 4,
        "intelligentContent": 27,
        "number_operators": 5,
        "number_operands": 10,
        "number_operators_unique": 2,
        "number_operands_unique": 6,
        "cloc": 0,
        "loc": 45,
        "lloc": 45,
        "mi": 52.23,
        "mIwoC": 52.23,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "package": "App\\Views\\",
        "pageRank": 0.05,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Views\\OrderTemplate",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "getOrderTemplate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "App\\Views\\BaseTemplate"
        ],
        "parents": [
            "App\\Views\\BaseTemplate"
        ],
        "implements": [],
        "lcom": 1,
        "length": 72,
        "vocabulary": 32,
        "volume": 360,
        "difficulty": 7.42,
        "effort": 2671.2,
        "level": 0.13,
        "bugs": 0.12,
        "time": 148,
        "intelligentContent": 48.52,
        "number_operators": 19,
        "number_operands": 53,
        "number_operators_unique": 7,
        "number_operands_unique": 25,
        "cloc": 0,
        "loc": 96,
        "lloc": 94,
        "mi": 38.66,
        "mIwoC": 38.66,
        "commentWeight": 0,
        "kanDefect": 0.45,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 2,
        "package": "App\\Views\\",
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Views\\ProductTemplate",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "getCardTemplate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getAllTemplate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 3,
        "ccnMethodMax": 2,
        "externals": [
            "App\\Views\\BaseTemplate"
        ],
        "parents": [
            "App\\Views\\BaseTemplate"
        ],
        "implements": [],
        "lcom": 2,
        "length": 87,
        "vocabulary": 39,
        "volume": 459.83,
        "difficulty": 4.11,
        "effort": 1891.87,
        "level": 0.24,
        "bugs": 0.15,
        "time": 105,
        "intelligentContent": 111.76,
        "number_operators": 15,
        "number_operands": 72,
        "number_operators_unique": 4,
        "number_operands_unique": 35,
        "cloc": 1,
        "loc": 73,
        "lloc": 72,
        "mi": 49.45,
        "mIwoC": 40.44,
        "commentWeight": 9.02,
        "kanDefect": 0.45,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1.5,
        "relativeSystemComplexity": 2.5,
        "totalStructuralComplexity": 2,
        "totalDataComplexity": 3,
        "totalSystemComplexity": 5,
        "package": "App\\Views\\",
        "pageRank": 0.03,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    }
]