var classes = [
    {
        "name": "App\\Config\\Config",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 0,
        "length": 9,
        "vocabulary": 9,
        "volume": 28.53,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0.01,
        "time": 0,
        "intelligentContent": 57.06,
        "number_operators": 0,
        "number_operands": 9,
        "number_operators_unique": 0,
        "number_operands_unique": 9,
        "cloc": 2,
        "loc": 16,
        "lloc": 14,
        "mi": 90.71,
        "mIwoC": 64.67,
        "commentWeight": 26.04,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\Config\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "App\\Controllers\\AboutController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Views\\AboutTemplate"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 8,
        "lloc": 8,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "package": "App\\Controllers\\",
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Controllers\\BasketController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "add",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "clear",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 5,
        "ccn": 4,
        "ccnMethodMax": 4,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 2,
        "length": 38,
        "vocabulary": 12,
        "volume": 136.23,
        "difficulty": 2.9,
        "effort": 395.06,
        "level": 0.34,
        "bugs": 0.05,
        "time": 22,
        "intelligentContent": 46.98,
        "number_operators": 9,
        "number_operands": 29,
        "number_operators_unique": 2,
        "number_operands_unique": 10,
        "cloc": 5,
        "loc": 31,
        "lloc": 26,
        "mi": 82.79,
        "mIwoC": 53.65,
        "commentWeight": 29.14,
        "kanDefect": 0.36,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\Controllers\\",
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "App\\Controllers\\HomeController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Views\\HomeTemplate"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 8,
        "lloc": 8,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "package": "App\\Controllers\\",
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Controllers\\OrderController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "create",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "sendMail",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 11,
        "ccn": 9,
        "ccnMethodMax": 5,
        "externals": [
            "App\\Services\\ProductFactory",
            "App\\Views\\OrderTemplate",
            "App\\Services\\ProductFactory",
            "App\\Services\\ValidateOrderData",
            "App\\Services\\OrderFactory",
            "PHPMailer\\PHPMailer\\PHPMailer"
        ],
        "parents": [],
        "implements": [],
        "lcom": 2,
        "length": 133,
        "vocabulary": 50,
        "volume": 750.63,
        "difficulty": 9.99,
        "effort": 7497.17,
        "level": 0.1,
        "bugs": 0.25,
        "time": 417,
        "intelligentContent": 75.15,
        "number_operators": 42,
        "number_operands": 91,
        "number_operators_unique": 9,
        "number_operands_unique": 41,
        "cloc": 21,
        "loc": 92,
        "lloc": 71,
        "mi": 71.99,
        "mIwoC": 38.27,
        "commentWeight": 33.72,
        "kanDefect": 0.8,
        "relativeStructuralComplexity": 169,
        "relativeDataComplexity": 0.52,
        "relativeSystemComplexity": 169.52,
        "totalStructuralComplexity": 507,
        "totalDataComplexity": 1.57,
        "totalSystemComplexity": 508.57,
        "package": "App\\Controllers\\",
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 5,
        "instability": 0.83,
        "violations": {}
    },
    {
        "name": "App\\Controllers\\ProductController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 7,
        "ccn": 7,
        "ccnMethodMax": 7,
        "externals": [
            "App\\Services\\ProductDBStorage",
            "App\\Models\\Product",
            "App\\Views\\ProductTemplate",
            "App\\Views\\ProductTemplate",
            "App\\Views\\ProductTemplate"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 37,
        "vocabulary": 16,
        "volume": 148,
        "difficulty": 12.21,
        "effort": 1807.71,
        "level": 0.08,
        "bugs": 0.05,
        "time": 100,
        "intelligentContent": 12.12,
        "number_operators": 18,
        "number_operands": 19,
        "number_operators_unique": 9,
        "number_operands_unique": 7,
        "cloc": 4,
        "loc": 28,
        "lloc": 24,
        "mi": 81.39,
        "mIwoC": 53.75,
        "commentWeight": 27.63,
        "kanDefect": 0.43,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1.67,
        "relativeSystemComplexity": 5.67,
        "totalStructuralComplexity": 4,
        "totalDataComplexity": 1.67,
        "totalSystemComplexity": 5.67,
        "package": "App\\Controllers\\",
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 3,
        "instability": 0.75,
        "violations": {}
    },
    {
        "name": "App\\Models\\Order",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "saveData",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Services\\ISaveStorage"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 13,
        "vocabulary": 6,
        "volume": 33.6,
        "difficulty": 2.5,
        "effort": 84.01,
        "level": 0.4,
        "bugs": 0.01,
        "time": 5,
        "intelligentContent": 13.44,
        "number_operators": 3,
        "number_operands": 10,
        "number_operators_unique": 2,
        "number_operands_unique": 4,
        "cloc": 1,
        "loc": 16,
        "lloc": 15,
        "mi": 82.41,
        "mIwoC": 63.52,
        "commentWeight": 18.88,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1.25,
        "relativeSystemComplexity": 2.25,
        "totalStructuralComplexity": 2,
        "totalDataComplexity": 2.5,
        "totalSystemComplexity": 4.5,
        "package": "App\\Models\\",
        "pageRank": 0.03,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Models\\Product",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "loadData",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getBasketData",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 7,
        "ccn": 5,
        "ccnMethodMax": 5,
        "externals": [
            "App\\Services\\ILoadStorage"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 67,
        "vocabulary": 16,
        "volume": 268,
        "difficulty": 8.33,
        "effort": 2233.33,
        "level": 0.12,
        "bugs": 0.09,
        "time": 124,
        "intelligentContent": 32.16,
        "number_operators": 17,
        "number_operands": 50,
        "number_operators_unique": 4,
        "number_operands_unique": 12,
        "cloc": 6,
        "loc": 43,
        "lloc": 37,
        "mi": 75.46,
        "mIwoC": 48.12,
        "commentWeight": 27.35,
        "kanDefect": 0.59,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1.33,
        "relativeSystemComplexity": 2.33,
        "totalStructuralComplexity": 3,
        "totalDataComplexity": 4,
        "totalSystemComplexity": 7,
        "package": "App\\Models\\",
        "pageRank": 0.04,
        "afferentCoupling": 2,
        "efferentCoupling": 1,
        "instability": 0.33,
        "violations": {}
    },
    {
        "name": "App\\Router\\Router",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "route",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 7,
        "ccn": 7,
        "ccnMethodMax": 7,
        "externals": [
            "App\\Controllers\\AboutController",
            "App\\Controllers\\ProductController",
            "App\\Controllers\\BasketController",
            "App\\Controllers\\OrderController",
            "App\\Controllers\\BasketController",
            "App\\Controllers\\HomeController"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 66,
        "vocabulary": 24,
        "volume": 302.61,
        "difficulty": 3.36,
        "effort": 1015.9,
        "level": 0.3,
        "bugs": 0.1,
        "time": 56,
        "intelligentContent": 90.14,
        "number_operators": 19,
        "number_operands": 47,
        "number_operators_unique": 3,
        "number_operands_unique": 21,
        "cloc": 4,
        "loc": 41,
        "lloc": 37,
        "mi": 70.74,
        "mIwoC": 47.48,
        "commentWeight": 23.26,
        "kanDefect": 0.37,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 1.75,
        "relativeSystemComplexity": 10.75,
        "totalStructuralComplexity": 9,
        "totalDataComplexity": 1.75,
        "totalSystemComplexity": 10.75,
        "package": "App\\Router\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 5,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Services\\DatabaseStorage",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "loadData",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "saveData",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Services\\IStorage"
        ],
        "parents": [],
        "implements": [
            "App\\Services\\IStorage"
        ],
        "lcom": 2,
        "length": 5,
        "vocabulary": 3,
        "volume": 7.92,
        "difficulty": 0.75,
        "effort": 5.94,
        "level": 1.33,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 10.57,
        "number_operators": 2,
        "number_operands": 3,
        "number_operators_unique": 1,
        "number_operands_unique": 2,
        "cloc": 2,
        "loc": 14,
        "lloc": 12,
        "mi": 97.66,
        "mIwoC": 70.03,
        "commentWeight": 27.63,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 3.5,
        "relativeSystemComplexity": 3.5,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 7,
        "totalSystemComplexity": 7,
        "package": "App\\Services\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Services\\DBStorage",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "PDO"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 2,
        "vocabulary": 2,
        "volume": 2,
        "difficulty": 0.5,
        "effort": 1,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 4,
        "number_operators": 1,
        "number_operands": 1,
        "number_operators_unique": 1,
        "number_operands_unique": 1,
        "cloc": 1,
        "loc": 10,
        "lloc": 9,
        "mi": 100.47,
        "mIwoC": 76.94,
        "commentWeight": 23.53,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\Services\\",
        "pageRank": 0.05,
        "afferentCoupling": 2,
        "efferentCoupling": 1,
        "instability": 0.33,
        "violations": {}
    },
    {
        "name": "App\\Services\\FileStorage",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "loadData",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "saveData",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 9,
        "ccn": 8,
        "ccnMethodMax": 5,
        "externals": [
            "App\\Services\\IStorage",
            "App\\Services\\ILoadStorage",
            "App\\Services\\ISaveStorage",
            "RuntimeException",
            "RuntimeException",
            "RuntimeException"
        ],
        "parents": [],
        "implements": [
            "App\\Services\\IStorage",
            "App\\Services\\ILoadStorage",
            "App\\Services\\ISaveStorage"
        ],
        "lcom": 2,
        "length": 76,
        "vocabulary": 17,
        "volume": 310.65,
        "difficulty": 13.09,
        "effort": 4066.65,
        "level": 0.08,
        "bugs": 0.1,
        "time": 226,
        "intelligentContent": 23.73,
        "number_operators": 28,
        "number_operands": 48,
        "number_operators_unique": 6,
        "number_operands_unique": 11,
        "cloc": 15,
        "loc": 62,
        "lloc": 47,
        "mi": 79.52,
        "mIwoC": 45,
        "commentWeight": 34.52,
        "kanDefect": 0.64,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 5.5,
        "relativeSystemComplexity": 5.5,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 11,
        "totalSystemComplexity": 11,
        "package": "App\\Services\\",
        "pageRank": 0.03,
        "afferentCoupling": 2,
        "efferentCoupling": 4,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "App\\Services\\OrderDBStorage",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "saveData",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "saveItems",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "App\\Services\\DBStorage",
            "App\\Services\\ISaveStorage"
        ],
        "parents": [
            "App\\Services\\DBStorage"
        ],
        "implements": [
            "App\\Services\\ISaveStorage"
        ],
        "lcom": 1,
        "length": 79,
        "vocabulary": 28,
        "volume": 379.78,
        "difficulty": 3.96,
        "effort": 1503.93,
        "level": 0.25,
        "bugs": 0.13,
        "time": 84,
        "intelligentContent": 95.9,
        "number_operators": 13,
        "number_operands": 66,
        "number_operators_unique": 3,
        "number_operands_unique": 25,
        "cloc": 6,
        "loc": 32,
        "lloc": 26,
        "mi": 81.88,
        "mIwoC": 50.8,
        "commentWeight": 31.08,
        "kanDefect": 0.38,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0.8,
        "relativeSystemComplexity": 16.8,
        "totalStructuralComplexity": 32,
        "totalDataComplexity": 1.6,
        "totalSystemComplexity": 33.6,
        "package": "App\\Services\\",
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "App\\Services\\OrderFactory",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "createOrder",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "App\\Models\\Order",
            "App\\Services\\FileStorage",
            "App\\Models\\Order",
            "App\\Services\\OrderDBStorage",
            "App\\Models\\Order"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 16,
        "vocabulary": 6,
        "volume": 41.36,
        "difficulty": 7,
        "effort": 289.52,
        "level": 0.14,
        "bugs": 0.01,
        "time": 16,
        "intelligentContent": 5.91,
        "number_operators": 9,
        "number_operands": 7,
        "number_operators_unique": 4,
        "number_operands_unique": 2,
        "cloc": 0,
        "loc": 16,
        "lloc": 16,
        "mi": 62.01,
        "mIwoC": 62.01,
        "commentWeight": 0,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 1,
        "package": "App\\Services\\",
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 3,
        "instability": 0.75,
        "violations": {}
    },
    {
        "name": "App\\Services\\ProductDBStorage",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "loadData",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Services\\DBStorage",
            "App\\Services\\ILoadStorage"
        ],
        "parents": [
            "App\\Services\\DBStorage"
        ],
        "implements": [
            "App\\Services\\ILoadStorage"
        ],
        "lcom": 1,
        "length": 13,
        "vocabulary": 8,
        "volume": 39,
        "difficulty": 1.5,
        "effort": 58.5,
        "level": 0.67,
        "bugs": 0.01,
        "time": 3,
        "intelligentContent": 26,
        "number_operators": 4,
        "number_operands": 9,
        "number_operators_unique": 2,
        "number_operands_unique": 6,
        "cloc": 0,
        "loc": 11,
        "lloc": 11,
        "mi": 66.01,
        "mIwoC": 66.01,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0.67,
        "relativeSystemComplexity": 4.67,
        "totalStructuralComplexity": 4,
        "totalDataComplexity": 0.67,
        "totalSystemComplexity": 4.67,
        "package": "App\\Services\\",
        "pageRank": 0.03,
        "afferentCoupling": 2,
        "efferentCoupling": 2,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Services\\ProductFactory",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "createProduct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "App\\Models\\Product",
            "App\\Services\\FileStorage",
            "App\\Models\\Product",
            "App\\Services\\ProductDBStorage",
            "App\\Models\\Product"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 16,
        "vocabulary": 6,
        "volume": 41.36,
        "difficulty": 7,
        "effort": 289.52,
        "level": 0.14,
        "bugs": 0.01,
        "time": 16,
        "intelligentContent": 5.91,
        "number_operators": 9,
        "number_operands": 7,
        "number_operators_unique": 4,
        "number_operands_unique": 2,
        "cloc": 0,
        "loc": 16,
        "lloc": 16,
        "mi": 62.01,
        "mIwoC": 62.01,
        "commentWeight": 0,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 1,
        "package": "App\\Services\\",
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 3,
        "instability": 0.75,
        "violations": {}
    },
    {
        "name": "App\\Services\\ValidateOrderData",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "validate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 10,
        "ccn": 10,
        "ccnMethodMax": 10,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 67,
        "vocabulary": 28,
        "volume": 322.09,
        "difficulty": 7.17,
        "effort": 2308.33,
        "level": 0.14,
        "bugs": 0.11,
        "time": 128,
        "intelligentContent": 44.94,
        "number_operators": 24,
        "number_operands": 43,
        "number_operators_unique": 7,
        "number_operands_unique": 21,
        "cloc": 4,
        "loc": 33,
        "lloc": 29,
        "mi": 74.87,
        "mIwoC": 49.19,
        "commentWeight": 25.68,
        "kanDefect": 0.5,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 7,
        "relativeSystemComplexity": 7,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 7,
        "totalSystemComplexity": 7,
        "package": "App\\Services\\",
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "App\\Views\\AboutTemplate",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "getTemplate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Views\\BaseTemplate"
        ],
        "parents": [
            "App\\Views\\BaseTemplate"
        ],
        "implements": [],
        "lcom": 1,
        "length": 15,
        "vocabulary": 8,
        "volume": 45,
        "difficulty": 1.67,
        "effort": 75,
        "level": 0.6,
        "bugs": 0.02,
        "time": 4,
        "intelligentContent": 27,
        "number_operators": 5,
        "number_operands": 10,
        "number_operators_unique": 2,
        "number_operands_unique": 6,
        "cloc": 0,
        "loc": 76,
        "lloc": 71,
        "mi": 47.91,
        "mIwoC": 47.91,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "package": "App\\Views\\",
        "pageRank": 0.04,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Views\\BaseTemplate",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "getTemplate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 22,
        "vocabulary": 13,
        "volume": 81.41,
        "difficulty": 4.69,
        "effort": 381.61,
        "level": 0.21,
        "bugs": 0.03,
        "time": 21,
        "intelligentContent": 17.37,
        "number_operators": 7,
        "number_operands": 15,
        "number_operators_unique": 5,
        "number_operands_unique": 8,
        "cloc": 52,
        "loc": 152,
        "lloc": 145,
        "mi": 78.43,
        "mIwoC": 39.07,
        "commentWeight": 39.36,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 1,
        "package": "App\\Views\\",
        "pageRank": 0.24,
        "afferentCoupling": 4,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "App\\Views\\HomeTemplate",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "getTemplate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 4,
        "ccnMethodMax": 4,
        "externals": [
            "App\\Views\\BaseTemplate"
        ],
        "parents": [
            "App\\Views\\BaseTemplate"
        ],
        "implements": [],
        "lcom": 1,
        "length": 62,
        "vocabulary": 33,
        "volume": 312.75,
        "difficulty": 5.22,
        "effort": 1633.26,
        "level": 0.19,
        "bugs": 0.1,
        "time": 91,
        "intelligentContent": 59.89,
        "number_operators": 15,
        "number_operands": 47,
        "number_operators_unique": 6,
        "number_operands_unique": 27,
        "cloc": 30,
        "loc": 137,
        "lloc": 125,
        "mi": 69.4,
        "mIwoC": 36.25,
        "commentWeight": 33.15,
        "kanDefect": 0.52,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 2,
        "package": "App\\Views\\",
        "pageRank": 0.04,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Views\\OrderTemplate",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "getOrderTemplate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 4,
        "ccnMethodMax": 4,
        "externals": [
            "App\\Views\\BaseTemplate"
        ],
        "parents": [
            "App\\Views\\BaseTemplate"
        ],
        "implements": [],
        "lcom": 1,
        "length": 102,
        "vocabulary": 45,
        "volume": 560.17,
        "difficulty": 7.28,
        "effort": 4075.97,
        "level": 0.14,
        "bugs": 0.19,
        "time": 226,
        "intelligentContent": 76.99,
        "number_operators": 23,
        "number_operands": 79,
        "number_operators_unique": 7,
        "number_operands_unique": 38,
        "cloc": 17,
        "loc": 177,
        "lloc": 153,
        "mi": 55.66,
        "mIwoC": 32.56,
        "commentWeight": 23.09,
        "kanDefect": 0.45,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 2,
        "package": "App\\Views\\",
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Views\\ProductTemplate",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "getAllTemplate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getCardTemplate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 9,
        "ccn": 8,
        "ccnMethodMax": 7,
        "externals": [
            "App\\Views\\BaseTemplate"
        ],
        "parents": [
            "App\\Views\\BaseTemplate"
        ],
        "implements": [],
        "lcom": 2,
        "length": 164,
        "vocabulary": 64,
        "volume": 984,
        "difficulty": 6.98,
        "effort": 6871.03,
        "level": 0.14,
        "bugs": 0.33,
        "time": 382,
        "intelligentContent": 140.92,
        "number_operators": 29,
        "number_operands": 135,
        "number_operators_unique": 6,
        "number_operands_unique": 58,
        "cloc": 18,
        "loc": 134,
        "lloc": 118,
        "mi": 59.66,
        "mIwoC": 32.77,
        "commentWeight": 26.89,
        "kanDefect": 1.21,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 2,
        "relativeSystemComplexity": 3,
        "totalStructuralComplexity": 2,
        "totalDataComplexity": 4,
        "totalSystemComplexity": 6,
        "package": "App\\Views\\",
        "pageRank": 0.03,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    }
]